// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJOdLOfW3GrDyJkzRDFSDwojkcscdw-_I',
    appId: '1:206805422163:web:0b0edb83eff1aa9695f6a6',
    messagingSenderId: '206805422163',
    projectId: 'foodie-app-f545b',
    authDomain: 'foodie-app-f545b.firebaseapp.com',
    storageBucket: 'foodie-app-f545b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7PZsEE6Ts8OpBZARadhxwn0_usHkd5n8',
    appId: '1:206805422163:android:76331e6f7582ee6595f6a6',
    messagingSenderId: '206805422163',
    projectId: 'foodie-app-f545b',
    storageBucket: 'foodie-app-f545b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_OkJS_YH0prCkUoYjBhOD4Tb8gcTSBlQ',
    appId: '1:206805422163:ios:c98b18173f733eda95f6a6',
    messagingSenderId: '206805422163',
    projectId: 'foodie-app-f545b',
    storageBucket: 'foodie-app-f545b.appspot.com',
    iosBundleId: 'com.example.foddieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_OkJS_YH0prCkUoYjBhOD4Tb8gcTSBlQ',
    appId: '1:206805422163:ios:c98b18173f733eda95f6a6',
    messagingSenderId: '206805422163',
    projectId: 'foodie-app-f545b',
    storageBucket: 'foodie-app-f545b.appspot.com',
    iosBundleId: 'com.example.foddieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJOdLOfW3GrDyJkzRDFSDwojkcscdw-_I',
    appId: '1:206805422163:web:9e5d1903e7b4591495f6a6',
    messagingSenderId: '206805422163',
    projectId: 'foodie-app-f545b',
    authDomain: 'foodie-app-f545b.firebaseapp.com',
    storageBucket: 'foodie-app-f545b.appspot.com',
  );
}
